server:
  port: 8080
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: cook,present
          contentType: application/json
        event-out:
          destination: menu
          contentType: application/json
# 수정
api:
  url:
    cook: http://localhost:8082
    coupon: http://localhost:8085


logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
  file: D:/logs/application.log

server:
  port: 8081
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: cook,present
          contentType: application/json
        event-out:
          destination: menu
          contentType: application/json
#수정
api:
  url:
    cook: http://cook:8080
    coupon: http://coupon:8080

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
  file: /mnt/aws/logs/order-application.log